# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171107_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=128)),
                ('division', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('linkedin', models.CharField(max_length=128)),
                ('photo', models.CharField(max_length=1024, null=True)),
            ],
        ),
    ]
